services:
  postgres:
    container_name: postgres_container
    image: postgres:18.1
    environment:
      POSTGRES_USER: tlsrk
      POSTGRES_PASSWORD: ecompass
      PGDATA: /data/postgres
      TZ: Asia/Kolkata
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - mono_ecom
    restart: unless-stopped


  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      TZ: Asia/Kolkata
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - mono_ecom
    restart: unless-stopped


networks:
  mono_ecom:
    driver: bridge

volumes:
  postgres:
  pgadmin:


